---
command: /Users/Bood/mypro/leela-zero/bin/leelaz -d -t 1 -p 1600 --noponder -w /Users/Bood/mypro/leela-zero/bin/af9
tests:
  # Ladder tests
  - name: ladder1.sgf
    sgf: ladder1.sgf
    group: ladder
    move: black
    no_move:
      - P7
  - name: ladder2
    sgf: ladder2.sgf
    group: ladder
    move: black
    no_move:
      - G4
  - name: ladder3
    sgf: ladder3.sgf
    group: ladder
    move: white
    no_move:
      - P11
  - name: ladder4
    sgf: ladder4.sgf
    group: ladder
    move: black
    no_move:
      - P6
  - name: ladder5
    sgf: ladder5.sgf
    group: ladder
    move: white
    no_move:
      - J6
  - name: ladder6
    sgf: ladder6.sgf
    group: ladder
    move: white
    no_move:
      - F14
  - name: ladder7
    sgf: ladder7.sgf
    group: ladder
    move: white
    no_move:
      - G6
  - name: 33point-ladder
    sgf: aq_lz_33point_ladder.sgf
    group: ladder
    number: 15
    move: black
    no_move:
      - Q7

  # Life & Death tests
  - name: lifedeath1
    sgf: lifedeath1.sgf
    group: lifedeath
    move: white
    yes_move:
      - M10
  - name: lifedeath2
    sgf: lifedeath2.sgf
    group: lifedeath
    number: 220
    move: white
    yes_move:
      - S19 # Secure top right corner
  - name: lifedeath3_easy
    sgf: zen7-LZaf9.sgf
    group: lifedeath
    move: white
    max_win_rate: 40

  # Large group sensitive tests
  - name: largegroup1
    sgf: largegroup1.sgf
    group: largegroup
    number: 294
    move: white
    yes_move:
      - E1
  - name: largegroup2
    sgf: zen7_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40
  - name: largegroup3
    sgf: jinduan(P)_LZ.sgf
    group: largegroup
    move: white
    max_win_rate: 40

  - name: endgame1
    sgf: endgame1.sgf
    group: endgame
    number: 289
    move: black
    yes_move:
      - S19

  - name: endgame2
    sgf: endgame2.sgf
    group: endgame
    number: 270
    move: white
    no_move:
      - G19

  # Capture Race tests
  - name: race1
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 63
    move: black
    yes_move:
      - S11

  - name: race2
    sgf: MaTianFang_LZ_20180227.sgf
    group: race
    number: 65
    move: black
    yes_move:
      - R10
